# Generated by Django 4.1.3 on 2022-11-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "price_per_quant",
                    models.FloatField(verbose_name="Price per quantity"),
                ),
                (
                    "description",
                    models.CharField(max_length=512, verbose_name="Description"),
                ),
                ("type", models.CharField(max_length=256, verbose_name="Type")),
                (
                    "packaging",
                    models.BooleanField(
                        default="False", verbose_name="Does it have packaging"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=256, verbose_name="Email")),
                ("password", models.CharField(max_length=256, verbose_name="Password")),
                ("name", models.CharField(max_length=256, verbose_name="Name Surname")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="Phone number"
                    ),
                ),
                ("address", models.CharField(max_length=256, verbose_name="Address")),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Pice")),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_buyer",
                        to="website.user",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_product",
                        to="website.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_seller",
                        to="website.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_seller",
                to="website.user",
            ),
        ),
    ]
