# Generated by Django 4.1.3 on 2022-11-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="lat",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="lon",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
    ]
