# Generated by Django 4.1.3 on 2022-11-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_customuser_lat_alter_customuser_lon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="lat",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="lon",
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
