# Generated by Django 4.1.3 on 2022-11-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_product_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=512, verbose_name="Title"),
        ),
    ]
