# Generated by Django 4.1.3 on 2022-11-06 01:22

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_product_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="date",
            field=models.DateField(default=datetime.date.today, verbose_name="Date"),
        ),
    ]
