# Generated by Django 4.1.3 on 2022-11-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_product_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.CharField(
                default="", max_length=512, verbose_name="Ingredients"
            ),
        ),
    ]
