# Generated by Django 4.1.3 on 2022-11-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_product_ingredients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="ingredients",
            field=models.CharField(max_length=512, verbose_name="Ingredients"),
        ),
    ]
