# Generated by Django 4.1.3 on 2022-11-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.CharField(
                default="DEF", max_length=256, verbose_name="address"
            ),
        ),
    ]
