# Generated by Django 4.1.3 on 2022-11-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_customuser_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.CharField(max_length=256, verbose_name="address"),
        ),
    ]
