# Generated by Django 4.1.3 on 2022-11-06 07:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_alter_customuser_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="food_type",
            field=models.CharField(
                choices=[
                    ("PACK", "Packaged food"),
                    ("COOK", "Cooked food"),
                    ("VEGE", "Vegetables"),
                    ("FRUT", "Fruits"),
                ],
                default="PACK",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ingredients",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=512, verbose_name="Ingredients"),
                size=None,
            ),
        ),
    ]
